// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/inventory/pb/inventory.proto

package inventoryPb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Search        string                 `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchReq) Reset() {
	*x = SearchReq{}
	mi := &file_internal_inventory_pb_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchReq) ProtoMessage() {}

func (x *SearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_inventory_pb_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchReq.ProtoReflect.Descriptor instead.
func (*SearchReq) Descriptor() ([]byte, []int) {
	return file_internal_inventory_pb_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *SearchReq) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type InventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryResponse) Reset() {
	*x = InventoryResponse{}
	mi := &file_internal_inventory_pb_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryResponse) ProtoMessage() {}

func (x *InventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_inventory_pb_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryResponse.ProtoReflect.Descriptor instead.
func (*InventoryResponse) Descriptor() ([]byte, []int) {
	return file_internal_inventory_pb_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *InventoryResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *InventoryResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_internal_inventory_pb_inventory_proto protoreflect.FileDescriptor

const file_internal_inventory_pb_inventory_proto_rawDesc = "" +
	"\n" +
	"%internal/inventory/pb/inventory.proto\x12\vinventoryPb\"#\n" +
	"\tSearchReq\x12\x16\n" +
	"\x06search\x18\x01 \x01(\tR\x06search\"7\n" +
	"\x11InventoryResponse\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name2X\n" +
	"\x14InventoryGrpcService\x12@\n" +
	"\x06Search\x12\x16.inventoryPb.SearchReq\x1a\x1e.inventoryPb.InventoryResponseB\x0fZ\r./inventoryPbb\x06proto3"

var (
	file_internal_inventory_pb_inventory_proto_rawDescOnce sync.Once
	file_internal_inventory_pb_inventory_proto_rawDescData []byte
)

func file_internal_inventory_pb_inventory_proto_rawDescGZIP() []byte {
	file_internal_inventory_pb_inventory_proto_rawDescOnce.Do(func() {
		file_internal_inventory_pb_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_inventory_pb_inventory_proto_rawDesc), len(file_internal_inventory_pb_inventory_proto_rawDesc)))
	})
	return file_internal_inventory_pb_inventory_proto_rawDescData
}

var file_internal_inventory_pb_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_inventory_pb_inventory_proto_goTypes = []any{
	(*SearchReq)(nil),         // 0: inventoryPb.SearchReq
	(*InventoryResponse)(nil), // 1: inventoryPb.InventoryResponse
}
var file_internal_inventory_pb_inventory_proto_depIdxs = []int32{
	0, // 0: inventoryPb.InventoryGrpcService.Search:input_type -> inventoryPb.SearchReq
	1, // 1: inventoryPb.InventoryGrpcService.Search:output_type -> inventoryPb.InventoryResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_inventory_pb_inventory_proto_init() }
func file_internal_inventory_pb_inventory_proto_init() {
	if File_internal_inventory_pb_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_inventory_pb_inventory_proto_rawDesc), len(file_internal_inventory_pb_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_inventory_pb_inventory_proto_goTypes,
		DependencyIndexes: file_internal_inventory_pb_inventory_proto_depIdxs,
		MessageInfos:      file_internal_inventory_pb_inventory_proto_msgTypes,
	}.Build()
	File_internal_inventory_pb_inventory_proto = out.File
	file_internal_inventory_pb_inventory_proto_goTypes = nil
	file_internal_inventory_pb_inventory_proto_depIdxs = nil
}
