// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package inventoryDi

import (
	"github.com/hifat/mallow-sale-embedding/internal/agent/repository"
	"github.com/hifat/mallow-sale-embedding/internal/inventory/handler"
	"github.com/hifat/mallow-sale-embedding/internal/inventory/repository"
	"github.com/hifat/mallow-sale-embedding/internal/inventory/service"
	"github.com/qdrant/go-client/qdrant"
	"github.com/tmc/langchaingo/llms/ollama"
)

// Injectors from wire.go:

func Init(llm *ollama.LLM, db *qdrant.Client) *inventoryHandler.Handler {
	iRepository := agentRepository.NewOllama(llm)
	inventoryRepositoryIRepository := inventoryRepository.NewQdrant(db)
	iService := inventoryService.New(iRepository, inventoryRepositoryIRepository)
	inventoryGrpc := inventoryHandler.NewGrpc(iService)
	handler := inventoryHandler.New(inventoryGrpc)
	return handler
}
